### ISSUE TITLE
Message in the package installation

### ISSUE THREAD

**Issue by JuanCrg90** [wolvesio/meteor-neat#2]
Hello, i'm try to install your package in my meteor app, but when i run the command

    meteor add wolves:neat

I have the next message

> While selecting package versions:
error: Potentially incompatible change required to top-level dependency: fourseven:scss 1.2.3, was 2.1.1.
Constraints on package "fourseven:scss":
* fourseven:scss@1.0.0 <- wolves:neat 1.0.0
To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the command line.

So, i had to use that flag  

    meteor add wolves:neat --allow-incompatible-update

Could be possible update the package for use with the most recent scss package versión

Cheers.

**Comment by outluch** [comment]
+1

**Comment by natecox** [comment]
Same here, needs a version update.

**Comment by natecox** [comment]
To those waiting on a fix for this, I've migrated to using a bower integration package that seems like an overall good solution for libraries such as neat and bourbon that don't need helpers, etc.: https://github.com/mquandalle/meteor-bower

**Comment by aleatorik** [comment]
Should be fixed with this PR - thank you

https://github.com/wolvesio/meteor-neat/pull/3
