### ISSUE TITLE
Needs an update to latest libsass and neat

### ISSUE THREAD

**Issue by mcrider** [wolvesio/meteor-neat#5]
Hey me again -- I had some dependency issues after updating the meteor-bitters you updated yesterday (thanks for that!) and got the same deprecation warnings in neat that I was getting bitters.  I went ahead and updated the dependency on fourseven:scss and dropped in the latest neat files and everything seems to be good now with no warnings in the log.  I'll submit a PR in a sec.

**Comment by mcrider** [comment]
Ok, PR at https://github.com/wolvesio/meteor-neat/pull/6, hope it helps

**Comment by aleatorik** [comment]
Its as though you read my mind. I actually updated before I looked at your issue:

https://github.com/wolvesio/meteor-neat/commits/master

I'm going to close your PR since I already pulled in the newest stuff, but I appreciate your help.
